[package]
name = "new_reflect"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { git = "https://github.com/MrGVSV/bevy.git", branch = "reflect-type-info", default-features = false }